# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/package_load_metrics.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'proto/package_load_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/package_load_metrics.proto\x12#devtools.build.lib.packages.metrics\x1a\x1egoogle/protobuf/duration.proto\"\xbc\x01\n\x12PackageLoadMetrics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x30\n\rload_duration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x13\n\x0bnum_targets\x18\x03 \x01(\x04\x12\x19\n\x11\x63omputation_steps\x18\x04 \x01(\x04\x12\x1c\n\x14num_transitive_loads\x18\x05 \x01(\x04\x12\x18\n\x10package_overhead\x18\x06 \x01(\x04\x42\x32\n.com.google.devtools.build.lib.packages.metricsP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.package_load_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.google.devtools.build.lib.packages.metricsP\001'
  _globals['_PACKAGELOADMETRICS']._serialized_start=106
  _globals['_PACKAGELOADMETRICS']._serialized_end=294
# @@protoc_insertion_point(module_scope)
