# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/strategy_policy.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'proto/strategy_policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/strategy_policy.proto\x12\x15\x62laze.strategy_policy\"\xdb\x01\n\x0eStrategyPolicy\x12>\n\x0fmnemonic_policy\x18\x01 \x01(\x0b\x32%.blaze.strategy_policy.MnemonicPolicy\x12\x44\n\x15\x64ynamic_remote_policy\x18\x02 \x01(\x0b\x32%.blaze.strategy_policy.MnemonicPolicy\x12\x43\n\x14\x64ynamic_local_policy\x18\x03 \x01(\x0b\x32%.blaze.strategy_policy.MnemonicPolicy\"u\n\x0eMnemonicPolicy\x12\x19\n\x11\x64\x65\x66\x61ult_allowlist\x18\x01 \x03(\t\x12H\n\x12strategy_allowlist\x18\x02 \x03(\x0b\x32,.blaze.strategy_policy.StrategiesForMnemonic\";\n\x15StrategiesForMnemonic\x12\x10\n\x08mnemonic\x18\x01 \x01(\t\x12\x10\n\x08strategy\x18\x02 \x03(\tB/\n+com.google.devtools.build.lib.runtime.protoP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.strategy_policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n+com.google.devtools.build.lib.runtime.protoP\001'
  _globals['_STRATEGYPOLICY']._serialized_start=55
  _globals['_STRATEGYPOLICY']._serialized_end=274
  _globals['_MNEMONICPOLICY']._serialized_start=276
  _globals['_MNEMONICPOLICY']._serialized_end=393
  _globals['_STRATEGIESFORMNEMONIC']._serialized_start=395
  _globals['_STRATEGIESFORMNEMONIC']._serialized_end=454
# @@protoc_insertion_point(module_scope)
